### ISSUE TITLE
插件工作不正常

### ISSUE THREAD

**Issue by DavidYin166** [pcrbot/picfinder_take#12]
之前安装的picfinder工作正常的，只不过后面由于ascii2d加了验证之后ascii2d用不了了，也就没管。
今天更新了最新的插件，然后插件就不工作了。
后台的输出如下

[2022-02-21 13:11:45,073 nonebot] INFO: Self: 456874316, Message -1354638914 from 835979419@[群:631687943]: '[CQ:at,qq=456874316] 搜图'
[2022-02-21 13:11:45,074 picfinder] INFO: Message -1354638914 triggered start_finder.
[2022-02-21 13:11:45,485 nonebot] INFO: Message -1354638914 is ignored: ServiceFunc of HoshinoBot finished.
0.735
too short, not likely a screen shot
[2022-02-21 13:11:56,199 image] INFO: Loading Image Search Container……
[2022-02-21 13:11:56,199 image] DEBUG: Loading all view……
[2022-02-21 13:11:56,199 image] DEBUG: Now starting get the SauceNAO data:https://gchat.qpic.cn/gchatpic_new/835979419/631687943-3181823672-118FCD68704D70C0FBA1884E2CF63B3B/0?term=3
[2022-02-21 13:11:57,839 image] ERROR: Traceback (most recent call last):
  File "/home/carlos/pcrbot/HoshinoBot/hoshino/modules/picfinder_take/image.py", line 567, in get_image_data_sauce
    result = await NAO.get_view(image_url)
  File "/home/carlos/pcrbot/HoshinoBot/hoshino/modules/picfinder_take/image.py", line 413, in get_view
    for sauce in sauces['results']:
KeyError: 'results'

[2022-02-21 13:11:57,840 image] ERROR: SauceNao not found imageInfo
[2022-02-21 13:11:57,840 image] INFO: Loading Image Search Container……
[2022-02-21 13:11:57,850 image] DEBUG: Loading all view……
[2022-02-21 13:11:57,850 image] DEBUG: Now starting get the https://ascii2d.net/search/url/https://gchat.qpic.cn/gchatpic_new/835979419/631687943-3181823672-118FCD68704D70C0FBA1884E2CF63B3B/0?term=3
[2022-02-21 13:11:58,470 image] ERROR: ascii2d not found imageInfo
[2022-02-21 13:11:59,225 nonebot] INFO: Self: 456874316, Message 1117370969 from 835979419@[群:631687943]: '[CQ:image,file=118fcd68704d70c0fba1884e2cf63b3b.image,url=https://gchat.qpic.cn/gchatpic_new/835979419/631687943-3181823672-118FCD68704D70C0FBA1884E2CF63B3B/0?term=3,subType=0]'
[2022-02-21 13:12:25,267 nonebot] INFO: Message -2017818442 is ignored: Handled by Hoshino

看上去似乎是插件在对返回的结果提取其中的部分数据时发生了错误，由于py请求这一块我一直不是很明白，无法调试，没办法只能发出这个issue，抱歉了。
![1703](https://user-images.githubusercontent.com/48946260/154894018-f8e92b88-82e0-495b-8f2d-9469f04ea635.png)

**Comment by DavidYin166** [comment]
还有一个问题就是，在感谢bot之后，bot没有反应，后台显示正常触发了 triggered thanks.
但是机器人在聊天里没有反应，而且搜图模式无法退出，再次发送搜图会提示还是在搜图模式，只能等到超时自动退出。
（虽然这一点并不是太影响使用，不过我考虑了一下，还是提出来吧。）

**Comment by assassingyk** [comment]
你打开你log中的这个图片链接就会发现是这个……
![image](https://user-images.githubusercontent.com/55473115/154947947-59e1ecf6-009f-4b38-be90-0ea9b08c6d72.png)

应该是qq的图片缓存服务器逐渐在加反盗图功能吧
这种只能说没什么办法，除非完全重构代码改成本地图片文件上传搜索的模式……

**Comment by assassingyk** [comment]
感谢无效的问题我这边没复现，命令本身是用“谢谢”做prefix的，triggered但没反应的话你确认一下是不是叫对了名字……机器人设置了多个昵称时默认只响应昵称列表里第一个昵称

**Comment by DavidYin166** [comment]
> 你打开你log中的这个图片链接就会发现是这个…… ![image](https://user-images.githubusercontent.com/55473115/154947947-59e1ecf6-009f-4b38-be90-0ea9b08c6d72.png)
> 
> 应该是qq的图片缓存服务器逐渐在加反盗图功能吧 这种只能说没什么办法，除非完全重构代码改成本地图片文件上传搜索的模式……

原来如此。。。那就是没办法了的事了。

**Comment by DavidYin166** [comment]
> 感谢无效的问题我这边没复现，命令本身是用“谢谢”做prefix的，triggered但没反应的话你确认一下是不是叫对了名字……机器人设置了多个昵称时默认只响应昵称列表里第一个昵称

至于感谢这个问题，如果是机器人设置了多个昵称时默认只响应昵称列表里第一个昵称的话，我再试试看看。
