### ISSUE TITLE
回复搜图报错

### ISSUE THREAD

**Issue by Gaylone** [pcrbot/picfinder_take#3]
can only concatenate tuple (not "str") to tuple
`[2021-07-26 11:35:03,539 picfinder] ERROR: <class 'TypeError'> occured when replymessage handling message -1331636577.
[2021-07-26 11:35:03,539 picfinder] ERROR: can only concatenate tuple (not "str") to tuple
Traceback (most recent call last):
  File "E:\OneDrive - Microsoft 365 Professional Plus\yobot和mirai框架\xcwbot\xcwbot\HoshinoBot\hoshino\service.py", line 188, in wrapper
    return await func(self.bot, ctx)
  File "E:\OneDrive - Microsoft 365 Professional Plus\yobot和mirai框架\xcwbot\xcwbot\HoshinoBot\hoshino\modules\picfinder_take\__init__.py", line 145, in replymessage
    if name+pfcmd in cmd:`

**Comment by assassingyk** [comment]
草，NICKNAME我只考虑了str和list，想不到还会有人用tuple格式存的，失策.jpg

**Comment by assassingyk** [comment]
修了，你再试试）
